### ISSUE TITLE
Add the ability to get FeatureData[Taxonomy] based on the tree

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/q2-fragment-insertion#1]

**Comment by sjanssen2** [comment]
In principle it should be possible to traverse the tree for every inserted fragment from the tip towards the root and collect all taxonomic labels on this path which should give you the lineage string.

@wasade is this a valid strategy? I remember you were concerned about the quality of the taxonomic labels. Which alternative would you suggest? RDP for the raw fragments?

Would we want to add this ability as another "method" or should the existing method simply return three objects/artifacts?

**Comment by wasade** [comment]
It's valid but the labels on the tree do not necessarily reflect Greengenes 13_8 and the discrepancy has not been understood. I think it would be fine for the existing method to return 3 objects.

**Comment by ElDeveloper** [comment]
Fixed in #9
